
project_structure:
    build: build
    contracts: contracts
    scripts: scripts
    tests: tests
    interfaces: interfaces
    reports: reports

networks:
    default: development    
    #default: avax-test
    development:
        host: https://127.0.0.1:8545
        
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        reverting_tx_gas_limit: max
        #reverting_tx_gas_limit: 6721975
        #persist: false
        default_contract_owner: true
        chainid: 1337
        test_rpc:
            cmd: ganache-cli
            port: 8545
            gas_limit: 6721975
            accounts: 10
            #evm_version: istanbul
            mnemonic: brownie          
    avax-test:
      host: "https://api.avax-test.network/ext/bc/C/rpc"
      explorer: https://api-testnet.snowtrace.io/api
    #   43113
    avax:
      host: "https://api.avax.network/ext/bc/C/rpc"
      explorer: https://api.snowtrace.io/api    

compiler:
    evm_version: null
    solc:
        version: 0.8.5
        optimizer:
            enabled: true
            runs: 200
        remappings:
            null #-"@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1"

#dependencies:
#    - smartcontractkit/chainlink-brownie-contracts@0.4.1

#brownie networks add live private host=https://127.0.0.1:8545 chainid=1337        