name: discord message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: send custom message with args
      uses: appleboy/discord-action@main
      with:
        webhook_id: 1100683807692161034
        webhook_token: MTEwMDY4MzgwNzY5MjE2MTAzNA.GDMjyc.bo9dEY4ofreQ9uqqcmOwb1E8cEqre5E_JgvOiQ
        args: The ${{ github.event_name }} event triggered first step.
